### ISSUE TITLE
extra element tag when using factory and request data to send request 

### ISSUE THREAD

**Issue by gitedunne** [andersinno/suds-jurko#2]
Using the latest from master, and python3 I am getting a strange issue.  

Here's the code:
someRequestMethod = theClient.factory.create("createUser")
someRequestMethod.username = "joeUser"
someRequestMethod.firstName = "joe"
someRequestMethod.lastName = "user"
someRequestMethod.email = "someEmail@thisIsAnEmail.com"
someRequestMethod.role = theRole
someRequestMethod.disabled = "false"
someRequestMethod.password = "thisIsMyPassword"
		
print("The createUserMethod: " )
print( str(someRequestMethod))
response = theClient.service.createUser( someRequestMethod )

Here's the log:

The createUserMethod: 
(createUser){
   username = "joeUser"
   firstName = "joe"
   lastName = "user"
   email = "someEmail@thisIsAnEmail.com"
   role = "User"
   password = "thisIsMyPassword"
   disabled = "false"
   attributes = 
      (ArrayOfTTUserAttribute){
         item[] = <empty>
      }
 }
ERROR:suds.client:<suds.sax.document.Document object at 0x1038a6748>

And here's what the post looks like (see that opening tags for `<username>` are there twice:
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://fs-tests-ws.theportal.int/v/2/soap/portal/"><SOAP-ENV:Header/><ns0:Body><ns1:createUser><username><username>joeUser</username><firstName>joe</firstName><lastName>user</lastName><email>someEmail@thisIsAnEmail.com</email><role>User</role><password>thisIsMyPassword</password><disabled>false</disabled></username><firstName/><lastName/><email/><role/><password/><disabled/></ns1:createUser></ns0:Body></SOAP-ENV:Envelope>
`

**Comment by charn** [comment]
Not entirely sure, but to me it looks like you might be creating a SUDS object out of the method and then assigning that object into the username field when you're calling the service method.

What does `print(theClient)` give you? I think you might need to do something like the following (maybe the latter one, but of course depending on your WSDL types).

```python
user_suds_obj = theClient.factory.create("UserTypeOrSomething")

user_suds_obj.username = "joeUser"
user_suds_obj.firstName = "joe"
user_suds_obj.lastName = "user"
user_suds_obj.email = "someEmail@thisIsAnEmail.com"
user_suds_obj.role = theRole
user_suds_obj.disabled = "false"
user_suds_obj.password = "thisIsMyPassword"

response = theClient.service.createUser(user=user_suds_obj)

### OR

response = theClient.service.createUser(
    username="joeUser"
    firstName="joe"
    lastName="user"
    email="someEmail@thisIsAnEmail.com"
    role=theRole
    disabled="false"
    password="thisIsMyPassword"
)
```

There's my two cents.

**Comment by gitedunne** [comment]
thanks for the response.  

yeah, that would make sense if the method signature and took a userObject of some kind similar to what you have above:  

`response = theClient.service.createUser(user=user_suds_obj)`

but it isn't unfortunately.  For this wsdl endpoint it accepts a list of strings (essentially).  Like this:

`response = theClient.service.createUser( testUserName, testUserFirstName, testUserLastNamet, testEmail, theRole, thePassword, False )` 

The result of the print(theClient) for that function def is:
`createUser(xs:string username, xs:string firstName, xs:string lastName, xs:string email, xs:string role, xs:boolean disabled, xs:string password, ArrayOfREUserAttribute attributes)`
            

What's interesting, and also why I think this is a bug is, if in my first example the username is set to be an empty string, the request is built correctly (other than the username being empty).
`user_suds_obj.username = ''  #so this works fine...other than it's blank in the soap request`

The post here : http://adcaes.org/2014/10/22/implementing-a-python-soap-client-with-suds/
suggests what I am trying to do is valid.  It makes the soap request a bit less fragile if the api parameter argument changed (for example). 

If I had a createUser method that was defined like : 
`createUser(xs:string username, xs:string firstName )`

or if it had the first name and username reversed like this : 
`createUser(xs:string firstName, xs:string userName )`

the consumer code wouldn't care if written like this:

```
someRequestData = theClient.factory.create("createUser")
someRequestData.username = "joeUser"
someRequestData.firstName = "joe"

response = theClient.service.createUser( someRequestData )
```

**Comment by charn** [comment]
Actually looking at the example: http://adcaes.org/2014/10/22/implementing-a-python-soap-client-with-suds/ it's basically the same what I described:

> ```python
> user_suds_obj = theClient.factory.create("UserTypeOrSomething")
> response = theClient.service.createUser(user=user_suds_obj)
> ```

In the weather example there's a line:
```python
result = client.service.getCityWeather(request_data)
```

I checked the the example and corresponding WSDL and what's being done in that previous line is equivalent to:
```python
result = client.service.getCityWeather(request=request_data)
```

So in the example the `getCityWeather` method is given a `CityWeatherRequest` object as a parameter which is also the only parameter the method will take, but in your situation `createUser` takes in a series of different parameters and there's just no way around that. :cry:

**Comment by gitedunne** [comment]
ok thanks for the response Charn.  I still feel as if using the method object should work.  It is strange that setting username to '' allows the soap request to be constructed properly (other than it being empty).  Setting the username to something non-empty causes the opening element tag to show up twice.

I do appreciate the thoughts/investigation.  I'll keep messing with it.  If I have any other insights I'll repost.

**Comment by charn** [comment]
I'm pretty sure using an instance of `createUser` suds object as an argument for the `createUser` service method will not work. The service method (`theClient.service.createUser`) doesn't expect an instance of a `createUser` suds object as an argument. As you pointed out with the method signature, correct arguments for the method are: `username`, `firstName`, `lastName`, `email`,  `role`, `disabled`, `password` and `attributes`.

In the first message you had the SOAP call (with indentation below).

```xml
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://fs-tests-ws.theportal.int/v/2/soap/portal/">
    <SOAP-ENV:Header/>
    <ns0:Body>
        <ns1:createUser>
            <username>
                <username>joeUser</username>
                <firstName>joe</firstName>
                <lastName>user</lastName>
                <email>someEmail@thisIsAnEmail.com</email>
                <role>User</role>
                <password>thisIsMyPassword</password>
                <disabled>false</disabled>
            </username>
            <firstName/>
            <lastName/>
            <email/>
            <role/>
            <password/>
            <disabled/>
        </ns1:createUser>
    </ns0:Body>
</SOAP-ENV:Envelope>
```

As you can clearly see from this an instance of `createUser` suds object has been assigned to the `username` field. This is due to giving an instance of `createUser` suds object as a single argument for the method, which means that in the method it's assigned to the `username` parameter because it's the first argument on the method signature.

You most likely are also receiving `ERROR:suds.client:<suds.sax.document.Document object at 0x1038a6748>` because `username` is now an instance of `createUser` which is not a string as SUDS expects.

I tried to hint the following in my previous message:
```python
response = theClient.service.createUser( someRequestMethod )
# This has exactly the same effect as
response = theClient.service.createUser(username=someRequestMethod)
```

:tada:

**Comment by gitedunne** [comment]
arg...yes I see, you are totally correct.  thanks for the follow up.
