### ISSUE TITLE
error in suds-jurko setup command: use_2to3 is invalid

### ISSUE THREAD

**Issue by nineleaps-vijay** [andersinno/suds-jurko#6]
Hi, I am facing this issue while trying to install suds-jurko.
My python version is 3.7.3 and pip version is 20.0.1
`ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-aq1d_1x5/suds-jurko_99c7f674655c40cb8b6582552bf426e5/setup.py'"'"'; __file__='"'"'/tmp/pip-install-aq1d_1x5/suds-jurko_99c7f674655c40cb8b6582552bf426e5/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-507p176x
         cwd: /tmp/pip-install-aq1d_1x5/suds-jurko_99c7f674655c40cb8b6582552bf426e5/
    Complete output (1 lines):
    error in suds-jurko setup command: use_2to3 is invalid.`

**Comment by danjsiegel1** [comment]
+1 for the same issue.

**Comment by nickyfoto** [comment]
https://github.com/pypa/setuptools/blob/main/CHANGES.rst

**Comment by aguthrie1190** [comment]
You can pin setuptools to 58.0.0 for a quick fix: 
`pip install 'setuptools==58.0.0'`

**Comment by nineleaps-vijay** [comment]
Yes, that worked, Thanks

**Comment by lassepe** [comment]
I' not sure this issue should be closed. It's still not fixed. Pinning setuptools is kind of a hacky workaround.

**Comment by mikealquimia** [comment]
> You can pin setuptools to 58.0.0 for a quick fix: `pip install 'setuptools==58.0.0'`

thanks! this worked for me

**Comment by AvnerCohen** [comment]
Forcing an old `setuptools` is far from a perfect solution here, It's an over 2 years old, `pip`, together with `setuptools` is moving forward.

I would suggest to open this and fix the core issue..

As in - https://github.com/andersinno/suds-jurko/pull/8

**Comment by casualuser** [comment]
any news here??
proper fix is really required nowadays but #8 is still opened

**Comment by AffanAhmedUsmani** [comment]
due to this many libraries with lates version cant be used as they werent there with this setup tool version was so suds jurko should solve this issue what ever it is as it's like very exhausting

**Comment by olivarius1** [comment]
> You can pin setuptools to 58.0.0 for a quick fix: `pip install 'setuptools==58.0.0'`

I also encountered this problem. Using setuptools==58.0.0 did not work, but setuptools==57.5.0 did.
